### ISSUE TITLE
can't handle http request

### ISSUE THREAD

**Issue by abuvanth** [pimoroni/phew#33]
2022-12-28 14:19:44 [debug    / 107kB] Get request
Task exception wasn't retrieved
future: <Task> coro= <generator object '_handle_request' at 20016650>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "/lib/phew/server.py", line 298, in _handle_request
  File "/lib/phew/template.py", line 7, in render_template
OSError: [Errno 2] ENOENT

**Comment by abuvanth** [comment]
i forgot to upload html file
