### ISSUE TITLE
Task exception wasn't retrieved future: <Task> coro= <generator object '_handle_request' at 20015230> Traceback (most recent call last):   File "asyncio/core.py", line 1, in run_until_complete   File "/lib/phew/server.py", line 277, in _handle_request AttributeError: 'NoneType' object has no attribute 'status'

### ISSUE THREAD

**Issue by jevylux** [pimoroni/phew#61]
I have a problem with the following code running on a raspberry pico with the image RPI_PICO_W-20240602-v1.23.0.uf2

`from phew import connect_to_wifi, server
from machine import Pin, PWM
import json

import network_cred
ip = connect_to_wifi(network_cred.SSID, network_cred.PASSWORD)
print("Connected to IP", ip)

.....

@server.route("/api/control-led", methods=["POST"])
def ledCommand(request):

    set_pwm_rgb(pwm_red, request.data["ledRed"])
    set_pwm_rgb(pwm_green, request.data["ledGreen"])
    set_pwm_rgb(pwm_blue, request.data["ledBlue"])
    return json.dumps({"message": "Command sent successfully!"}), 200, {"Content-Type": "application/json"}

@server.catchall()
def catchall(request):
  return "Not found", 404

server.run()`

When sending a POST request i get the following error :

Task exception wasn't retrieved
future: <Task> coro= <generator object '_handle_request' at 20015230>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "/lib/phew/server.py", line 277, in _handle_request
AttributeError: 'NoneType' object has no attribute 'status'

**Comment by andrewpbrooker** [comment]
Hi

I am getting the same error as you

Did you get anywhere with it ?

Thanks

Andy

**Comment by jevylux** [comment]
Hi, i am on holiday right now. I will check when i am back home mid of next weekRegardsMarcSent from my iPhoneOn 14 Oct 2024, at 19:32, andrewpbrooker ***@***.***> wrote:﻿
Hi
I am getting the same error as you
Did you get anywhere with it ?
Thanks
Andy

**Comment by star-glider** [comment]
Do you have a catchall route defined for GET as well? I was seeing this because of browser favicon requests. If you set up a catchall (even it doesn't actually do anything), that might fix the problem.

**Comment by sjgcornish** [comment]
Hi  
Any further progess on this error. I have a catchall
@server.catchall()
def catchall(request):
  return "Not found", 404

Note this error is caused by submitting a form by submitting with no value in the html input type.

Also I note that if a Imove away from the page (i.e. go to another tab I get error  need more than 0 values to unpack.

2025-11-13 18:17:08 [debug    / 154kB] > parsed template: index.html (took 4 ms)
2025-11-13 18:17:08 [info     / 152kB] > GET / (200 OK) [3680ms]
2025-11-13 18:20:56 [error    / 150kB] need more than 0 values to unpack
